### ISSUE TITLE
Nachrichtenarchiv-Menü und Eventliste-Menü kaputt

### ISSUE THREAD

**Issue by lennier83** [Paratron/contao-mod-mobile-visibility#2]
Hallo.

Habe gerade das super modul getestet, dabei ist mir aufgefallen, dass die Archiv-Menüs nicht mehr korrekt (bzw. so gut wie garnicht) angezeigt werden.
contao 3.0.3
Habe auch die Erweiterung "teaserimages" installiert, nur zur Info.
Nachdem ich kiss deinstalliert habe, war wieder alles korrekt.

**Comment by Paratron** [comment]
Was sind Archiv-Menüs und in wie fern werden sie nicht mehr angezeigt? Ein Screenshot mit vorher/nachher Vergleich wäre prima, damit ich damit was anfangen kann.

**Comment by lennier83** [comment]
Sorry.
Anbei Screenshots.
Modultypen "Nachrichtenarchiv-Menü" (Nachrichten) und "Eventliste-Menü" (Events).

![event2](https://f.cloud.github.com/assets/3589232/155489/d581dbee-764c-11e2-8682-7b7632081af4.jpg)
![event1](https://f.cloud.github.com/assets/3589232/155491/de293e4a-764c-11e2-91d5-a258ae6b8c28.jpg)

**Comment by lennier83** [comment]
Hier noch das, was contao anzeigt beim Debugen:

Warning: Invalid argument supplied for foreach() in /usr/www/users/.../system/modules/calendar/templates/mod_eventmenu.html5 on line 13

#0 /usr/www/users/babjjm/bildung/system/modules/calendar/templates/mod_eventmenu.html5(13): __error(2, 'Invalid argumen...', '/usr/www/users/...', 13, Array)
#1 /usr/www/users/babjjm/bildung/system/modules/core/library/Contao/Template.php(255): include('/usr/www/users/...')
#2 /usr/www/users/babjjm/bildung/system/modules/core/classes/FrontendTemplate.php(37): Contao\Template->parse()
#3 /usr/www/users/babjjm/bildung/system/modules/core/modules/Module.php(165): Contao\FrontendTemplate->parse()
#4 /usr/www/users/babjjm/bildung/system/modules/calendar_extended/modules/ModuleCalendarExt.php(143): Contao\Module->generate()
#5 /usr/www/users/babjjm/bildung/system/modules/calendar_extended/modules/ModuleEventMenuExt.php(50): Contao\ModuleCalendarExt->generate()
#6 /usr/www/users/babjjm/bildung/system/modules/core/elements/ContentModule.php(63): Contao\ModuleEventMenuExt->generate()
#7 /usr/www/users/babjjm/bildung/system/modules/core/library/Contao/Controller.php(446): Contao\ContentModule->generate()
#8 /usr/www/users/babjjm/bildung/system/modules/core/modules/ModuleArticle.php(179): Contao\Controller->getContentElement(Object(Contao\Model\Collection))
#9 /usr/www/users/babjjm/bildung/system/modules/core/modules/Module.php(148): Contao\ModuleArticle->compile()
#10 /usr/www/users/babjjm/bildung/system/modules/core/modules/ModuleArticle.php(59): Contao\Module->generate()
#11 /usr/www/users/babjjm/bildung/system/modules/core/library/Contao/Controller.php(374): Contao\ModuleArticle->generate(false)
#12 /usr/www/users/babjjm/bildung/system/modules/core/library/Contao/Controller.php(227): Contao\Controller->getArticle(Object(Contao\Model\Collection), false, false, 'left')
#13 /usr/www/users/babjjm/bildung/system/modules/core/pages/PageRegular.php(109): Contao\Controller->getFrontendModule('0', 'left')
#14 /usr/www/users/babjjm/bildung/index.php(250): Contao\PageRegular->generate(Object(Contao\PageModel))
#15 /usr/www/users/babjjm/bildung/index.php(411): Index->run()
#16 {main}

**Comment by Paratron** [comment]
Mit den Infos kann ich leider auch nicht viel mehr anfangen. Hast du das Visibility Modul lediglich aktiviert, oder auch Einstellungen damit vorgenommen?

**Comment by lennier83** [comment]
Hallo nochmal.
Ähm. Nob. Ich habe dein Modul laut Anweisung eingerichtet (keine Einstellungen, nur installiert und hier und da getestet mit sichtbar/unsichtbar). Es funktioniert auch wunderbar. Nur wenn es zu News/Events-Archiv-Menüs kommt, klappt irgendetwas nicht. Hier habe ich aber auch nichts anderes gemacht als standard-einstellungen.

Vielleicht liegt das auch an einer anderen extension, wobei ich die zu testzwecken deaktiviert habe. Nada.
Werde auch nochmal bei einer frischen Installation sehen demnächst ...

Alternativ kannst du sehr gerne bei Zeit ein "Nachrichtenarchiv-Menü" unter "Module" unter contao 3 anlegen und schauen ob es bei dir klappt.

Großen Dank für diese Extension und beste Grüße aus Berlin bis hierhin.

**Comment by getthemax** [comment]
Das mit dem Nachrichten-Archiv kann ich bestätigen.

**Comment by Metis77** [comment]
kann ich auch bestätigen.
Ein fix wäre genial !

**Comment by epsreps** [comment]
ich habe auch gerade diesen fehler entdeckt. ich benutze die erweiterun sehr gern. so wie ich das feststellen konnte ist die gateKeeperPage funktion in der helper class das problem.

**Comment by epsreps** [comment]
unter https://github.com/ecmpages/contao-mod-mobile-visibility habe ich die gateKeeperPage funktion erweitert. nun funktionierts auch mit dem archivmenu. vielleicht kann man das in die originale version einarbeiten

**Comment by Metis77** [comment]
1+

**Comment by Paratron** [comment]
Wenn mir die Anderen bei denen der Bug auftreten bestätigen können, das @ecmpages Lösung jetzt eindfrei funktioniert, werde ich das gerne hier im Project mergen :)
