### ISSUE TITLE
Uninstall?

### ISSUE THREAD

**Issue by ulriklyhne** [Paratron/contao-mod-mobile-visibility#5]
How do I uninstall "contao-mod-mobile-visibility" module?

**Comment by stefanschleich** [comment]
Delete the folder `/system/modules/kiss_mobile-visibility` in your contao folder and trigger a database update in the extension manager or install tool.

**Comment by ulriklyhne** [comment]
Hi Stefan.
This is what happens once I delete /system/modules/kiss_mobile-visibility, and trigger a database update in the extension manager

Any other suggestions?

Warning: include(/var/www/afv.dk/public_html/system/modules/kiss_mobile-visibility/modules/kiss_mobile_visibility_helper.php) [function.include<http://php.net/manual/en/function.include>]: failed to open stream: No such file or directory in system/modules/core/library/Contao/ClassLoader.php on line 148
#0 system/modules/core/library/Contao/ClassLoader.php(148): __error(2, 'include(/var/ww...', '/var/www/afv.dk...', 148, Array)
#1 system/modules/core/library/Contao/ClassLoader.php(148): Contao\ClassLoader::load()
#2 [internal function]: Contao\ClassLoader::load('kiss_mobile_vis...')
#3 [internal function]: spl_autoload_call('kiss_mobile_vis...')
#4 system/modules/core/library/Contao/System.php(140): get_class_methods('kiss_mobile_vis...')
#5 system/modules/core/library/Contao/Template.php(272): Contao\System->import('kiss_mobile_vis...')
#6 system/modules/core/classes/BackendTemplate.php(34): Contao\Template->parse()
#7 system/modules/core/classes/BackendModule.php(100): Contao\BackendTemplate->parse()
#8 system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#9 system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()
#10 system/modules/core/classes/Backend.php(423): RepositoryManager->generate()
#11 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_mana...')
#12 contao/main.php(20): Contao\BackendMain->run()
#13 {main}


Best Regards

Ulrik Lyhne
Technical Supervisor

[cid:image001.png@01D3218A.3650BA20]
Skovgaardsgade 3
8000 Aarhus C
Denmark
T:    +45 88 33 11 88
M  : +45 27 52 75 55
www.afv.dk

Fra: Stefan Schleich <notifications@github.com>
Svar til: Paratron/contao-mod-mobile-visibility <reply@reply.github.com>
Dato: tirsdag den 29. august 2017 kl. 15.26
Til: Paratron/contao-mod-mobile-visibility <contao-mod-mobile-visibility@noreply.github.com>
Cc: Ulrik Lyhne <ul@afv.dk>, Author <author@noreply.github.com>
Emne: Re: [Paratron/contao-mod-mobile-visibility] Uninstall? (#5)


Delete the folder /system/modules/kiss_mobile-visibility in your contao folder and trigger a database update in the extension manager or install tool.

**Comment by ulriklyhne** [comment]
Hi Stefan.
I really need your help on this.
When I follow your advise: ” Delete the folder /system/modules/kiss_mobile-visibility in your contao folder and trigger a database update in the extension manager or install tool.”
and trigger a database update in the extension manager. Then I get this error, and my webside is uavailable.
 

Warning: include(/var/www/afv.dk/public_html/system/modules/kiss_mobile-visibility/modules/kiss_mobile_visibility_helper.php) [function.include]: failed to open stream: No such file or directory in system/modules/core/library/Contao/ClassLoader.php on line 148
#0 system/modules/core/library/Contao/ClassLoader.php(148): __error(2, 'include(/var/ww...', '/var/www/afv.dk...', 148, Array)
#1 system/modules/core/library/Contao/ClassLoader.php(148): Contao\ClassLoader::load()
#2 [internal function]: Contao\ClassLoader::load('kiss_mobile_vis...')
#3 [internal function]: spl_autoload_call('kiss_mobile_vis...')
#4 system/modules/core/library/Contao/System.php(140): get_class_methods('kiss_mobile_vis...')
#5 system/modules/core/library/Contao/Template.php(272): Contao\System->import('kiss_mobile_vis...')
#6 system/modules/core/classes/BackendTemplate.php(34): Contao\Template->parse()
#7 system/modules/core/classes/BackendModule.php(100): Contao\BackendTemplate->parse()
#8 system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#9 system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()
#10 system/modules/core/classes/Backend.php(423): RepositoryManager->generate()
#11 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_mana...')
#12 contao/main.php(20): Contao\BackendMain->run()
#13 {main}
 
Any other suggestions to how I uninstall the Kiss mobile-visibility extension?
 
Best Regards
 
Ulrik Lyhne 
Technical Supervisor
Aarhus Film Workshop

**Comment by stefanschleich** [comment]
Hi Ulrik,

there still seems to be something that wants to load the module. Are you sure you deleted the extension or did you just rename the folder? Without looking into the system I can't be of much help, sorry.

**Comment by ulriklyhne** [comment]
Just a rename. Is´nt that enough? Do I need to remove it completly?

**Comment by ulriklyhne** [comment]
Took a copy local of the folder, and delete the folder online. Same problem :(
